name: thumbnail-api
services:
- name: thumbnail-api
  github:
    branch: main
    deploy_on_push: true
    repo: leenapagdar/ThumbnailAPI
  build_command: mvn clean package -DskipTests
  envs:
  - key: SPRING_PROFILES_ACTIVE
    value: prod
  - key: JAVA_TOOL_OPTIONS
    value: -Xmx512m -Xms256m
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
static_sites: []
